language: ruby

services:
  - postgresql

script:
  - RAILS_ENV=test bundle exec rake db:create
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/

before_script:
  - psql -c 'create database HolidayV1_test;' -U postgres
